//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErasmusAppTVZ.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErasmusAppTVZ.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string ApplicationBarAboutMenuItem {
            get {
                return ResourceManager.GetString("ApplicationBarAboutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide map.
        /// </summary>
        public static string ApplicationBarHideMap {
            get {
                return ResourceManager.GetString("ApplicationBarHideMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        public static string ApplicationBarOptions {
            get {
                return ResourceManager.GetString("ApplicationBarOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        public static string ApplicationBarOptionsMenuItem {
            get {
                return ResourceManager.GetString("ApplicationBarOptionsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string ApplicationBarProfileMenuItem {
            get {
                return ResourceManager.GetString("ApplicationBarProfileMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show map.
        /// </summary>
        public static string ApplicationBarShowMap {
            get {
                return ResourceManager.GetString("ApplicationBarShowMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort.
        /// </summary>
        public static string ApplicationBarSort {
            get {
                return ResourceManager.GetString("ApplicationBarSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string ApplicationCancel {
            get {
                return ResourceManager.GetString("ApplicationCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cities.
        /// </summary>
        public static string ApplicationCitiesPageTitle {
            get {
                return ResourceManager.GetString("ApplicationCitiesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to countries.
        /// </summary>
        public static string ApplicationCountriesPageTitle {
            get {
                return ResourceManager.GetString("ApplicationCountriesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string ApplicationLoginPageTitle {
            get {
                return ResourceManager.GetString("ApplicationLoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to erasmus.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to professor.
        /// </summary>
        public static string LoginProfessor {
            get {
                return ResourceManager.GetString("LoginProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to student.
        /// </summary>
        public static string LoginStudent {
            get {
                return ResourceManager.GetString("LoginStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remember me.
        /// </summary>
        public static string MessageBoxRemember {
            get {
                return ResourceManager.GetString("MessageBoxRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want your preferences to be remembered?.
        /// </summary>
        public static string MessageBoxRememberCaption {
            get {
                return ResourceManager.GetString("MessageBoxRememberCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you choose to save your preferences, you will no longer see this screen.
        ///If you want to change them later, you can easily access preference options located in Application Bar..
        /// </summary>
        public static string MessageBoxRememberText {
            get {
                return ResourceManager.GetString("MessageBoxRememberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events.
        /// </summary>
        public static string PanoramaEventsPageTitle {
            get {
                return ResourceManager.GetString("PanoramaEventsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to students.
        /// </summary>
        public static string PanoramaStudentsPageTitle {
            get {
                return ResourceManager.GetString("PanoramaStudentsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to universities.
        /// </summary>
        public static string PanoramaUniversitiesPageTitle {
            get {
                return ResourceManager.GetString("PanoramaUniversitiesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to age.
        /// </summary>
        public static string ProfileAge {
            get {
                return ResourceManager.GetString("ProfileAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacts.
        /// </summary>
        public static string ProfileContacts {
            get {
                return ResourceManager.GetString("ProfileContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create profile.
        /// </summary>
        public static string ProfileCreatorTitle {
            get {
                return ResourceManager.GetString("ProfileCreatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit profile.
        /// </summary>
        public static string ProfileEditTitle {
            get {
                return ResourceManager.GetString("ProfileEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gender.
        /// </summary>
        public static string ProfileGender {
            get {
                return ResourceManager.GetString("ProfileGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hometown.
        /// </summary>
        public static string ProfileHomeCity {
            get {
                return ResourceManager.GetString("ProfileHomeCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country.
        /// </summary>
        public static string ProfileHomeCountry {
            get {
                return ResourceManager.GetString("ProfileHomeCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to university.
        /// </summary>
        public static string ProfileHomeUniversity {
            get {
                return ResourceManager.GetString("ProfileHomeUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interests.
        /// </summary>
        public static string ProfileInterests {
            get {
                return ResourceManager.GetString("ProfileInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to languages.
        /// </summary>
        public static string ProfileLanguages {
            get {
                return ResourceManager.GetString("ProfileLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full name.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading cities....
        /// </summary>
        public static string ProgressIndicatorCities {
            get {
                return ResourceManager.GetString("ProgressIndicatorCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading countries....
        /// </summary>
        public static string ProgressIndicatorCountries {
            get {
                return ResourceManager.GetString("ProgressIndicatorCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading programs....
        /// </summary>
        public static string ProgressIndicatorPrograms {
            get {
                return ResourceManager.GetString("ProgressIndicatorPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading universities....
        /// </summary>
        public static string ProgressIndicatorUniversities {
            get {
                return ResourceManager.GetString("ProgressIndicatorUniversities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
